#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from utils import pipeline_func

######
# business functions

def file_pkg(fname):
    from os import path
    import analyzer
    pkg = analyzer.file_summerize(fname)
    host = path.basename(path.splitext(fname)[0])
    pkg['host'] = host
    return pkg

def dir_summerize(dirname):
    import glob, os
    files = glob.glob(os.path.join(dirname, '*.txt'))
    s = map(file_pkg, files)
    s = filter(lambda x: x, s)
    return s

def result_sorting(sums):
    from analyzer import pkg_score
    return sorted(sums, key=pkg_score)

def result_beauty(sums):
    from analyzer import pkg_score
    def formatting(pkg):
        score = int(pkg_score(pkg) * 100)
        pkg['graph'] = '{score:.>{width}d}]'.format(width=score, score=score)
        return '<a href="./site?host=%(host)s">%(host)32s</a>, %(loss)4.1f%%, %(avg)7.2f, %(stddev)6.2f, %(graph)s' % \
                pkg
    return map(formatting, sums)

def analyzing(dirname):
    s = pipeline_func(dirname, [
        dir_summerize,
        result_sorting,
        result_beauty,
        ])
    title = '%32s %6s %8s %7s  %s' % ('host', 'loss', 'avg', 'stddev', 'graph')
    s.insert(0, title)
    return s


#####
# Script

# enable debugging
import cgitb
cgitb.enable()

table = analyzing("collection")

print "Content-Type: text/html;charset=utf-8"
print
print """
<head>
<style>
a:link {
text-decoration: none;
}

a:visited {
text-decoration: none;
}

a:hover {
text-decoration: underline;
}

a:active {
text-decoration: underline;
}
</style>
</head>
"""
print '<pre>'
for line in table:
    print line
print '</pre>'

